# Strangler / proxy inverso: Nginx → Gunicorn (servicio "web" en docker-compose).
# Más adelante: location /api/v2/ → otro backend (patrón Strangler).

upstream django_backend {
    server web:8000;
}

server {
    listen 80;
    server_name _;

    location = /favicon.ico {
        access_log off;
        log_not_found off;
    }

    location / {
        proxy_pass http://django_backend;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    # Nota: en el futuro, location /api/v2/ { proxy_pass http://otro_microservicio; }
}
